---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/

something: something-from-the-test-service-01

# this will cause a random, unused port to be assigned if none is specified)
server:
  port: ${PORT:${SERVER_PORT:0}}



